// <auto-generated />
using System;
using Contract.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contract.Data.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    [Migration("20191206164028_RemovingUnusedColumnsFromContractDataAndSubjectRole")]
    partial class RemovingUnusedColumnsFromContractDataAndSubjectRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contract.Core.Contract.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContractCode")
                        .IsRequired();

                    b.Property<DateTime>("CreationTime");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Contract.Core.Contract.ContractData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContractId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<DateTime?>("DateAccountOpened");

                    b.Property<DateTime?>("DateOfLastPayment");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("NextPaymentDate");

                    b.Property<int>("PhaseOfContract");

                    b.Property<DateTime?>("RealEndDate");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("ContractsData");
                });

            modelBuilder.Entity("Contract.Core.Individual.Individual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContractId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("CustomerCode")
                        .IsRequired();

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<int?>("Gender");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("NationalId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("Contract.Core.SubjectRole.SubjectRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContractId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("CustomerCode")
                        .IsRequired();

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("RoleOfCustomer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("SubjectRole");
                });

            modelBuilder.Entity("Contract.Core.Contract.ContractData", b =>
                {
                    b.HasOne("Contract.Core.Contract.Contract", "Contract")
                        .WithOne("ContractData")
                        .HasForeignKey("Contract.Core.Contract.ContractData", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Contract.Core.Money", "CurrentBalance", b1 =>
                        {
                            b1.Property<long>("ContractDataId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Currency");

                            b1.Property<decimal?>("Value")
                                .IsRequired();

                            b1.HasKey("ContractDataId");

                            b1.ToTable("ContractsData");

                            b1.HasOne("Contract.Core.Contract.ContractData")
                                .WithOne("CurrentBalance")
                                .HasForeignKey("Contract.Core.Money", "ContractDataId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Contract.Core.Money", "InstallmentAmount", b1 =>
                        {
                            b1.Property<long>("ContractDataId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int?>("Currency");

                            b1.Property<decimal?>("Value");

                            b1.HasKey("ContractDataId");

                            b1.ToTable("ContractsData");

                            b1.HasOne("Contract.Core.Contract.ContractData")
                                .WithOne("InstallmentAmount")
                                .HasForeignKey("Contract.Core.Money", "ContractDataId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Contract.Core.Money", "OriginalAmount", b1 =>
                        {
                            b1.Property<long>("ContractDataId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int?>("Currency");

                            b1.Property<decimal?>("Value");

                            b1.HasKey("ContractDataId");

                            b1.ToTable("ContractsData");

                            b1.HasOne("Contract.Core.Contract.ContractData")
                                .WithOne("OriginalAmount")
                                .HasForeignKey("Contract.Core.Money", "ContractDataId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Contract.Core.Money", "OverdueBalance", b1 =>
                        {
                            b1.Property<long>("ContractDataId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int?>("Currency");

                            b1.Property<decimal?>("Value");

                            b1.HasKey("ContractDataId");

                            b1.ToTable("ContractsData");

                            b1.HasOne("Contract.Core.Contract.ContractData")
                                .WithOne("OverdueBalance")
                                .HasForeignKey("Contract.Core.Money", "ContractDataId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Contract.Core.Individual.Individual", b =>
                {
                    b.HasOne("Contract.Core.Contract.Contract", "Contract")
                        .WithMany("Individuals")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Contract.Core.SubjectRole.SubjectRole", b =>
                {
                    b.HasOne("Contract.Core.Contract.Contract", "Contract")
                        .WithMany("SubjectRoles")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Contract.Core.Money", "GuranateeAmount", b1 =>
                        {
                            b1.Property<long>("SubjectRoleId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int?>("Currency");

                            b1.Property<decimal?>("Value");

                            b1.HasKey("SubjectRoleId");

                            b1.ToTable("SubjectRole");

                            b1.HasOne("Contract.Core.SubjectRole.SubjectRole")
                                .WithOne("GuranateeAmount")
                                .HasForeignKey("Contract.Core.Money", "SubjectRoleId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
